seo:
  site_name: Multifaceted Me - Discovering all we can be. 
  title: Multifaceted Me - Discovering all we can be. 
  description: Ready to push your limits and live your best life? Multifaceted Me offers inspiration, goal-setting tips, and helps you unlock your full potential. Dive in and be part of the Community!
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username: