seo:
  site_name: Unscripted - A year of Living on my own Terms
  title: Unscripted - A year of Living on my own Terms
  description: >-
    Step into the captivating world of a mid-thirties woman's sabbatical
    journey. Dive into her world of learning, wellness, and adventure, featuring
    surfing, meditation, yoga, and web development.
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username: